---
version: "3.1"
services:
  database:
    image: postgres
    container_name: postgres
    restart: unless-stopped

    ports:
      - "25432:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "django-test"
